name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci

    - name: Build and deploy
      run: |
        npm run build
        npx gh-pages -d build
      env:
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}